spring:
  application:
    name: admin-template
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/vue3_admin_template?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: admin
    password: 123456

  jackson:
    # 格式化全局时间字段 年-月-天 时：分：秒
    date-format: yyyy-MM-dd HH:mm:ss
    # 指定时间区域类型 东8区时区 既北京时间
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl